# ROBOT : 'talos' 
# TASK  : normal force task


# General 
dt: 0.01                                                      # OCP integration step 
N_h: 400                                                      # Horizon length in nodes
maxiter: 100                                                  # Max number of iterations in DDP
# q0: [ 1.7305e-01, -2.0000e-04, -5.2537e-01,  0., 0., 0.1, 0.] # Initial robot joint configuration
q0: [ 1.4399,  0.    , -1.1781,  0.    ,  0.    ,  0.    , -0.5236]
dq0: [0.,0.,0.,0.,0.,0.,0.]                                   # Initial robot joint velocity



# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'gripper_left_joint'



# Contact model 
CONTACT: 'True'                         # 'True' or 'False' 
contactModelType: '6D'                  # select in ['1D', '3D', '6D'] (cf. Crocoddyl contact models)
contactModelFrameName: 'DEFAULT'        # 'DEFAULT' = $(frame_of_interest)
contactModelTranslationRef: 'DEFAULT'   # Position of contact frame in WORLD frame 
contactModelRotationRef: 'DEFAULT'      # Orientation of contact frame in WORLD frame (! for '6D' contact only !)
contactModelGains: [0., 0.]             # Baumgarte stabilization gains 

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['force', 'stateReg', 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [0., 0., 1., 0., 0., 0.]
frameForceWeight: 10.
frameForceRef: [0., 0., -20, 0., 0., 0.]    
frameForceFrameName: 'DEFAULT'

 # 'friction' : end-effector frame friction cone 
mu:  0.5
frictionConeWeight: 1
frictionConeFrameName: 'DEFAULT'

 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.05
stateRegWeightTerminal: 1
stateRegRef: 'DEFAULT'

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegRef: 'DEFAULT' # reference not used for 'ctrlRegGrav'

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 0.]
frameTranslationWeight: 100
frameTranslationWeightTerminal: 100
frameTranslationRef: 'DEFAULT' # 'CIRCLE' ?
frameTranslationFrameName: 'DEFAULT'

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: 10
frameVelocityWeightTerminal: 10
frameVelocityRef: 'DEFAULT'    
frameVelocityFrameName: 'DEFAULT'


 # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 10.
frameRotationWeightTerminal: 10.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'DEFAULT'


 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
stateLimRef: 'DEFAULT'

 # 'ctrlLim' : torque limits
ctrlBounds: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
ctrlLimRef: 'DEFAULT'

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]