# OCP parameters for end-effector reaching task

# General 
f_c: 2                                               # Low-pass filter cut-off frequency
dt: 0.01                                             # OCP integration step 
N_h: 400                                             # Horizon length in nodes
maxiter: 1000                                           # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity
tau0: [0., -2.5503, -0.52852, -0.021027, 0.0000000013604, -0.36474, 0.] # Initial robot joint torque

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'translation', 'velocity',
WHICH_COSTS: ['translation', 'stateReg', 'velocity' , 'ctrlRegGrav']  

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0. ,0., 1., 1., 1., 1., 1., 1., 1.]
stateRegWeight: 0.01
stateRegWeightTerminal: 1
stateRegRef: 'DEFAULT' # TRACKING ?

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.005
ctrlRegWeightTerminal: 0.
ctrlRegRef: 'DEFAULT'  # reference not used for 'ctrlRegGrav'

# 'wReg' : unfiltered torque regularization
wRegWeight: 0.00002

# 'wLim' : unfiltered torque limit
wLimWeight: 10.

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 100.
frameTranslationWeightTerminal: 100.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'contact'
frameCircleTrajectoryRadius: 0.1  # in m
frameCircleTrajectoryVelocity: 3. # in rad/s

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: 0.
frameVelocityWeightTerminal: 100
frameVelocityRef: 'DEFAULT'    
frameVelocityFrameName: 'contact'

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
stateLimRef: 'DEFAULT'

 # 'ctrlLim' : torque limits
ctrlBounds: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
ctrlLimRef: 'DEFAULT'

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]