# OCP parameters for end-effector reaching task

# # Goal placement M = ( M_ee.rot @ rpyToMat(0, pi/2, 0) , [0.3, 0., 0.7] )
#   R =
#    -0.918754     0.389418    0.0651533
#     0.388443     0.921061   -0.0275464
#   -0.0707372 -2.41653e-08    -0.997495
#   p = 0.3   0 0.7
# # Starting config for IK (to avoid self-collision solution)
# q_init =  [-0.2263,  0.    , -0.174 , -1.6865,  0.0358,  1.5   , -0.3946]
# # Solution of IK_placement(q_init, M)
# q0 = [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]

# General 
LPF_TYPE: 1
f_c: 2                                                               # Low-pass filter cut-off frequency
dt: 0.01                                                             # OCP integration step 
N_h: 400                                                             # Horizon length in nodes
maxiter: 1000                                                        # Max number of iterations in DDP
q0: [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]  # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                                          # Initial robot joint velocity
tau0: [  0., -16.4279,  -0.,  14.4554, -0.6963, 0.027, 0.]           # Initial robot joint torque


# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'translation', 'velocity',
# WHICH_COSTS: ['translation', 'stateReg', 'velocity' , 'ctrlRegGrav']  
WHICH_COSTS: ['translation', 'stateReg', 'ctrlRegGrav']  

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0. ,0., 1., 1., 1., 1., 1., 1., 1.]
stateRegWeight: 0.01
stateRegWeightTerminal: 1
stateRegRef: 'DEFAULT' # TRACKING ?

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.005
ctrlRegWeightTerminal: 0.
ctrlRegRef: 'DEFAULT'  # reference not used for 'ctrlRegGrav'

# 'wReg' : unfiltered torque regularization
wRegWeight: 0.0001

# 'wLim' : unfiltered torque limit
wLimWeight: 10.

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 100.
frameTranslationWeightTerminal: 100.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'contact'
frameCircleTrajectoryRadius: 0.1  # in m
frameCircleTrajectoryVelocity: 2. # in rad/s

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: 0.
frameVelocityWeightTerminal: 100
frameVelocityRef: 'DEFAULT'    
frameVelocityFrameName: 'contact'

 # 'placement' : end-effector frame placement (translation + rotation)
framePlacementWeights:  [1., 1., 1., 0., 0., 0.]
framePlacementWeight: 0.1
framePlacementWeightTerminal: .1
framePlacementTranslationRef: 'DEFAULT'
framePlacementRotationRef: 'DEFAULT'
framePlacementFrameName: 'contact'

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
stateLimRef: 'DEFAULT'

 # 'ctrlLim' : torque limits
ctrlBounds: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
ctrlLimRef: 'DEFAULT'

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]