# OCP parameters for static end-effector pose reaching task

# General
dt: 0.05                                             # OCP integration step 
N_h: 1000                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity

# Cost function composition (a.k.a which terms will be actually used in the OCP)
WHICH_COSTS: ['stateReg', 'velocity', 'translation', 'ctrlReg'] # placement, etc.

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0. ,0., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: .1
stateRegWeightTerminal: 1

 # 'ctrlReg' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01

p_des: [-0.5, -0.5, 0.7]   # both translation and placement

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 1.
frameTranslationWeightTerminal: 10. 

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 0., 0., 0.]
frameVelocityWeight: 0.1
frameVelocityWeightTerminal: 10.
v_des: [0., 0., 0.]       

 # 'stateLim' : state limits
stateLimWeight: 0.
stateLimWeightTerminal: 0.

 # 'ctrlLim' : torque limits
u_lim: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeight: 0.

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]