# MPC parameters for static end-effector pose reaching task
# + PyBullet simulation


# MPC & sim parameters
simu_freq: 1000        # Simulation frequency in Hz
ctrl_freq: 1000        # Control frequency
plan_freq: 1000        # Planning frequency
T_tot: .1              # Simu duration (s)
# Simulation options
DELAY_SIM: False                # Add delay in reference torques (low-level)
DELAY_OCP: False                # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: False             # Affine scaling of reference torque
NOISE_TORQUES: False            # Add Gaussian noise on reference torques
FILTER_TORQUES: False           # Moving average smoothing of reference torques
NOISE_STATE: False             # Add Gaussian noise on the measured state 
FILTER_STATE: False             # Moving average smoothing of reference torques
SAVE_DATA: False                 # Save plot_data to npz
RECORD_SOLVER_DATA: False       # Keep trace of Vxx, Riccati gains, reg, Jacobian etc. (more data to save)
INIT_LOG: True                  # Initial logs summarizing parameters
init_log_display_time: 1        # How long (s) to display the initial logs ?
LOG: True                       # Logs during simulation
log_rate: 500                  # Display sim status once very 'log_rate' sim cycles




# General
dt: 0.01                                             # OCP integration step 
N_h: 100                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity

# Cost function composition (a.k.a which terms will be actually used in the OCP)
WHICH_COSTS: ['force', 'stateReg', 'velocity', 'translation', 'ctrlReg'] # placement, etc.

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [1., 1., 1., 1., 1., 1.]
frameForceWeight: 1.
f_des: [0., 0., 20, 0., 0., 0.]    

 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0. ,0., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: .001
stateRegWeightTerminal: 10.

 # 'ctrlReg' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegWeightTerminal: 10.

p_des: 'None'  # both translation and placement

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 1.
frameTranslationWeightTerminal: 10. 

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 0., 0., 0.]
frameVelocityWeight: 0.00
frameVelocityWeightTerminal: 10.
v_des: [0., 0., 0.]       

 # 'stateLim' : state limits
stateLimWeight: 0.
stateLimWeightTerminal: 0.

 # 'ctrlLim' : torque limits
u_lim: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeight: 0.

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]



# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.95
alpha_max: 1.05
beta_min: -0.1
beta_max: 0.1
  # White noise on desired torque and measured state
var_u: [3.0, 3.0, 2.0, 2.0, 1.0, 0.1, 0.1]
var_q: 0.028 #x10
var_v: 0.028 #x10
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 2 # in HF cycles
  # Proportional-integral torque control gains
Kp: [.2, .2, .2, .2, .2, .2, .2  ]
Ki: [.001, .001, .001, .001, .001, .001, .01]
Kd: [.00001, .00001, .00001, .00001, .00001, .00001, .00001]
u_avg_filter_length: 20 #8 # in HF cycles
x_avg_filter_length: 5  #20 #8 # in HF cycles