# Static pose reaching task
# Used for MPC simulations with and without torque tracking

# # # # # # # # 
# SIMULATION  #
# # # # # # # # 
# Frequencies
simu_freq: 1000 # Simulation frequency in Hz
ctrl_freq: 500  # Control frequency
plan_freq: 500  # Planning frequency
f_c: 20          # Low-pass filter cut-off frequency
# MPC
T_tot: 2.    # Simu duration (s)
dt: 0.03       # OCP integration step 
N_h: 100      # Horizon length in nodes
maxiter: 100   # Max number of iterations in DDP
# Initial robot state
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]
dq0: [0.,0.,0.,0.,0.,0.,0.]
tau0: [0., -2.3274, 0., 0.012262, 0., -0.010595, 0.]
# Simulation options
TORQUE_TRACKING: False         # Activate low-level reference torque tracking (PID) 
DELAY_SIM: False              # Add delay in reference torques (low-level)
DELAY_OCP: False               # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: False           # Affine scaling of reference torque
NOISE_TORQUES: False          # Add Gaussian noise on reference torques
FILTER_TORQUES: False         # Moving average smoothing of reference torques
NOISE_STATE: False             # Add Gaussian noise on the measured state 
FILTER_STATE: False            # Moving average smoothing of reference torques
INTERPOLATE_PLAN: True       # Interpolate DDP desired feedforward torque to control frequency
INTERPOLATE_CTRL: False       # Interpolate motor driver reference torque and time-derivatives to low-level frequency 
# Initial logs
INIT_LOGS: False
log_display_time: 2
# Save plot_data to npz
SAVE_DATA: False

# # # # # 
# TASK  # 
# # # # #
# State regularization 
stateRegWeights: [1., 1., 1., 1., 1., 1., 1., 4., 4., 4., 4., 4., 4., 4.]
xRegWeight: 0.5
xRegWeightTerminal: 0.1
# Torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
uRegWeight: 0.01
# State limits
xLimWeight: 100.
xLimWeightTerminal: 100.
# Torque limits
u_lim: [320, 320, 176, 176, 110, 40, 40]
uLimWeight: 1.
# Frame placement 
p_des: [0.5, -0.5, 0.7]  # Desired end-effector position
framePlacementWeights:  [1., 1., 1., 1., 1., 1.]
frameWeight: 2.
framePlacementWeightTerminal: 10.
# Frame velocity
frameVelocityWeightTerminal: 1000.
# armature
armature: [.1, .1, .1, .1, .1, .1, .01]

# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.90
alpha_max: 1.10
beta_min: -0.5
beta_max: 0.5
  # White noise on desired torque and measured state
# var_u: [3.0, 3.0, 2.0, 2.0, 1.0, 0.1, 0.1]
var_q: 0.028 #x10
var_v: 0.028 #x10
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 1 # in HF cycles
  # Proportional-integral torque control gains
Kp: [.2, .2, .2, .2, .2, .2, .2  ]
Ki: [.001, .001, .001, .001, .001, .001, .01]
Kd: [.00001, .00001, .00001, .00001, .00001, .00001, .00001]
u_avg_filter_length: 20 #8 # in HF cycles
x_avg_filter_length: 5  #20 #8 # in HF cycles