# OCP parameters for static end-effector contact force task

# General
dt: 0.01                                             # OCP integration step 
N_h: 200                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity

# Cost function composition (a.k.a which terms will be actually used in the OCP)
WHICH_COSTS: ['force', 'friction', 'stateReg', 'ctrlReg'] # placement, etc.

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [1., 1., 1., 1., 1., 1.]
frameForceWeight: 10.
f_des: [0., 0., -20, 0., 0., 0.]    

 # 'friction' : end-effector frame friction cone 
mu:  0.5
frictionConeWeight: 1

 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.1
stateRegWeightTerminal: 0.1

 # 'ctrlReg' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegRef: [0., 0., 0., 0., 0., 0., 0.]

p_des: 'None'  # both translation and placement

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 1.
frameTranslationWeightTerminal: .1 

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: .1
frameVelocityWeightTerminal: .1
v_des: [0., 0., 0.]       

 # 'stateLim' : state limits
stateLimWeight: 0.
stateLimWeightTerminal: 0.

 # 'ctrlLim' : torque limits
u_lim: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeight: 0.

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]