# OCP parameters for static end-effector pose reaching task

# General
f_c: 50                                         # Low-pass filter cut-off frequency
dt: 0.01                                             # OCP integration step 
N_h: 100                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity
tau0: [0., -2.5503, -0.52852, -0.021027, 0.0000000013604, -0.36474, 0.] # Initial robot joint torque

# Cost function composition (a.k.a which terms will be actually used in the OCP)
WHICH_COSTS: ['ctrlReg'] # 'ctrlReg'] # 'stateLim'] # ctrlLim, velocity, placement, etc.

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateRegWeight: .0
stateRegWeightTerminal: 0.

 # 'ctrlReg' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.

 # 'stateLim' : state limits
stateLimWeight: 0.
stateLimWeightTerminal: 0.

 # 'ctrlLim' : torque limits
u_lim: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeight: 0.

 # 'placement' : end-effector frame placement (translation + rotation)
framePlacementWeights:  [1., 1., 1., 1., 1., 1.]
framePlacementWeight: 0.0
framePlacementWeightTerminal: 0. #1000

p_des: [-0.5, -0.5, 0.7]  # both translation and placement

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 0.
frameTranslationWeightTerminal: 0. #1000

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeight: 0.
frameVelocityWeightTerminal: 0. #1000

# armature
armature: [.1, .1, .1, .1, .1, .1, .01]