# Static pose reaching task
# Used for MPC simulations with and without torque tracking

#Â OCP
dt: 0.05        # OCP integration step 
N_h: 658         # Horizon length in nodes
maxiter: 1000    # Max number of iterations in DDP
# Initial robot state
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]
dq0: [0.,0.,0.,0.,0.,0.,0.]

# State regularization 
stateRegWeights: [0., 0., 0., 0., 0., 0., 0., 2., 1., 1., 2., 3., 2., 3.]
stateRegWeight: 0.1
stateRegWeightTerminal: 1000.
# Torque regularization 
ctrlRegWeights: [1., 1., 1., 2., 2., 1., 1.]
ctrlRegWeight: 0.01
# State limits
stateLimWeight: 10.
stateLimWeightTerminal: 10.
# Torque limits
ctrl_lim: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeight: 10.
# Frame placement 
p_des: [-0.3, -0.3, 0.3]  # Desired end-effector position
framePlacementWeights:  [1., 1., 1., 1., 1., 1.]
framePlacementWeight: 1.5
framePlacementWeightTerminal: 20000.
# Frame velocity
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: 0.5
frameVelocityWeightTerminal: 5000
# armature
armature: [.1, .1, .1, .1, .1, .1, .01]