# Static pose reaching task
# Used for MPC simulations with and without torque tracking

#Â OCP
dt: 0.01        # OCP integration step 
N_h: 100     # Horizon length in nodes
maxiter: 100   # Max number of iterations in DDP
# Initial robot state
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]
dq0: [0.,0.,0.,0.,0.,0.,0.]

# State regularization 
stateRegWeights: [1., 1., 1., 1., 1., 1., 1., 4., 4., 4., 4., 4., 4., 4.]
stateRegWeight: .1
stateRegWeightTerminal: .1
# Torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: .01
# State limits
stateLimWeight: 10.
stateLimWeightTerminal: 10.
# Torque limits
ctrl_lim: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeight: 10.
# Frame placement 
p_des: [-0.5, -0.5, 0.7]  # Desired end-effector position
framePlacementWeights:  [1., 1., 1., 1., 1., 1.]
framePlacementWeight: 0.
framePlacementWeightTerminal: 10. #1000
# Frame velocity
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: 0.
frameVelocityWeightTerminal: 1. #1000
# armature
armature: [.1, .1, .1, .1, .1, .1, .01]