# MPC parameters for static end-effector pose reaching task
# + PyBullet simulation


# MPC & sim parameters
simu_freq: 2000        # Simulation frequency in Hz
ctrl_freq: 1000         # Control frequency
plan_freq: 500          # Planning frequency
T_tot: .2               # Simu duration (s)
# Simulation options
TORQUE_TRACKING: False          # Activate low-level reference torque tracking (PID) 
DELAY_SIM: False                # Add delay in reference torques (low-level)
DELAY_OCP: False                # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: False            # Affine scaling of reference torque
NOISE_TORQUES: False            # Add Gaussian noise on reference torques
FILTER_TORQUES: False           # Moving average smoothing of reference torques
NOISE_STATE: False              # Add Gaussian noise on the measured state 
FILTER_STATE: False             # Moving average smoothing of reference torques
INTERPOLATE_PLAN_TO_CTRL: False # Interpolate DDP desired feedforward torque to control frequency
INTERPOLATE_CTRL_TO_SIMU: False # Interpolate motor driver reference torque and time-derivatives to low-level frequency 
SAVE_DATA: True                 # Save plot_data to npz
INIT_LOG: True                  # Initial logs summarizing parameters
init_log_display_time: 1        # How long (s) to display the initial logs ?
LOG: True                       # Logs during simulation
log_rate: 1000                  # Display sim status once very 'log_rate' sim cycles





# General
f_c: 50                                              # Low-pass filter cut-off frequency
dt: 0.04                                             # OCP integration step 
N_h: 100                                             # Horizon length in nodes
maxiter: 10                                          # Max number of iterations in DDP
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity
tau0: [0., -2.3274, 0., 0.012262, 0., -0.010595, 0.] # Initial robot joint torque

# Cost function composition (a.k.a which terms will be actually used in the OCP)
WHICH_COSTS: ['translation', 'velocity', 'ctrlReg', 'stateReg', 'stateLim'] # placement, etc.

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0. ,0., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: .01
stateRegWeightTerminal: 1.

 # 'ctrlReg' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.001

 # 'stateLim' : state limits
stateLimWeight: 1.
stateLimWeightTerminal: 1.

 # 'ctrlLim' : torque limits
u_lim: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeight: 0.

 # 'placement' : end-effector frame placement (translation + rotation)
framePlacementWeights:  [1., 1., 1., 1., 1., 1.]
framePlacementWeight: 0
framePlacementWeightTerminal: 0. 

p_des: [-0.5, -0.5, 0.7]  # both translation and placement

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 0.5
frameTranslationWeightTerminal: 1. 

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 0., 0., 0.]
frameVelocityWeight: 0.00
frameVelocityWeightTerminal: 1.
v_des: [0., 0., 0.]       

# armature
armature: [.1, .1, .1, .1, .1, .1, .01]



# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.90
alpha_max: 1.10
beta_min: -0.5
beta_max: 0.5
  # White noise on desired torque and measured state
# var_u: [3.0, 3.0, 2.0, 2.0, 1.0, 0.1, 0.1]
var_q: 0.028 #x10
var_v: 0.028 #x10
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 1 # in HF cycles
  # Proportional-integral torque control gains
Kp: [.2, .2, .2, .2, .2, .2, .2  ]
Ki: [.001, .001, .001, .001, .001, .001, .01]
Kd: [.00001, .00001, .00001, .00001, .00001, .00001, .00001]
u_avg_filter_length: 20 #8 # in HF cycles
x_avg_filter_length: 5  #20 #8 # in HF cycles