# Static pose reaching task

# OCP
dt: 0.03          # OCP integration step 
N_h: 200         # Horizon length in nodes
maxiter: 1000     # Max number of iterations in DDP
# Initial robot state
q0: [0.1, 0.7, 0., 0.7, -0.5, 1.5, 0.]
dq0: [0.,0.,0.,0.,0.,0.,0.]

# State regularization 
stateRegWeights: [0., 0., 0., 0., 0., 0., 0., 1., 2., 1., 1., 1., 1., 1.]
stateRegWeight: .2 #.02
stateRegWeightTerminal: .2 #.02
# Torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01


# State limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.1
stateLimWeightTerminal: 0.1
# # Torque limits
# ctrl_lim: [320, 320, 176, 176, 110, 40, 40]
# ctrlLimWeight: 10.


# # Frame placement 
# p_des: [-0.3, -0.4, 0.5]  # Desired end-effector position
# framePlacementWeights:  [1., 1., 1., 1., 1., 1.]
# framePlacementWeight: 1.5
# framePlacementWeightTerminal: 1.5 
# Frame translation 
p_des: [-0.3, -0.4, 0.5]  
frameTranslationWeights: [1., 1., 1.]
frameTranslationWeight: 2.
frameTranslationWeightTerminal: 2.
# Frame velocity
# frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
# frameVelocityWeight: .01
# frameVelocityWeightTerminal: .01


# # Frame placement ELBOW # Positive distance to ground
# frameTranslationElbowWeights:  [1., 1., 1.]
# frameTranslationElbowWeight: 5.
# frameTranslationElbowWeightTerminal: 5. 
# # Frame placement HAND7
# frameTranslationHandWeights: [0., 0., 10.]
# frameTranslationHandWeight:  100.
# frameTranslationHandWeightTerminal: 1.

# armature
armature: [.1, .1, .1, .1, .1, .1, .01]