# ROBOT : 'talos' 
# TASK  : circle trajectory tracking


# General 
dt: 0.01                                                      # OCP integration step 
N_h: 400                                                      # Horizon length in nodes
maxiter: 100                                                  # Max number of iterations in DDP
# q0: [ 1.7305e-01, -2.0000e-04, -5.2537e-01,  0., 0., 0.1, 0.] # Initial robot joint configuration
q0: [ 1.4399,  0.    , -1.1781,  0.    ,  0.    ,  0.    , -0.5236]
dq0: [0.,0.,0.,0.,0.,0.,0.]                                   # Initial robot joint velocity


# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'gripper_left_joint'

#   R =
#   0.910888     0.0002  -0.412654
# -0.0712318   0.985065  -0.156759
#    0.40646   0.172184   0.897298
#   p = 0.5 0.3 0.1

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'translation', 'velocity',
WHICH_COSTS: ['translation', 'stateReg', 'ctrlRegGrav', 'stateLim']  

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.01
stateRegWeightTerminal: 0.01
stateRegRef: 'DEFAULT'  # 'DEFAULT' = [q0, v0]

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.001
ctrlRegRef: 'DEFAULT'   # DEFAULT = g(q) | NOT used for 'ctrlRegGrav' cost

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 10.
frameTranslationWeightTerminal: 10.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'DEFAULT'   # 'DEFAULT' = $(frame_of_interest)
frameCircleTrajectoryRadius: 0.1       # in m
frameCircleTrajectoryVelocity: 1.5     # in rad/s
CIRCLE_LOCAL_PLANE: 'XZ'               # LOCAL plane in which the circle lies

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: .1
frameVelocityWeightTerminal: .1
frameVelocityRef: 'DEFAULT'      
frameVelocityFrameName: 'DEFAULT'   # 'DEFAULT' = $(frame_of_interest) 

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 100.
stateLimWeightTerminal: 100.
stateLimRef: 'DEFAULT'            # 'DEFAULT' = [0., 0., 0., 0., 0., 0. ,0.]

 # 'ctrlLim' : torque limits
ctrlBounds: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
ctrlLimRef: 'DEFAULT'           # 'DEFAULT' = [0., 0., 0., 0., 0., 0. ,0.]

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]