# OCP parameters for end-effector reaching task

# General
dt: 0.02                                             # OCP integration step 
N_h: 200                                             # Horizon length in nodes
maxiter: 100                                         # Max number of iterations in DDP
q0: [2., 0., 0., 0., 0., 0., 0.]    # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                          # Initial robot joint velocity


frame_of_interest: 'gripper_left_joint'

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['stateReg', 'velocity', 'translation', 'ctrlRegGrav'] 

# Cost terms weights, activations and references
 # 'stateReg' : state regularization  
stateRegWeights: [0., 0., 0., 0., 0., 0. ,0., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: .1
stateRegWeightTerminal: 2.
stateRegRef: 'DEFAULT'

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.01
ctrlRegRef: 'DEFAULT' # reference not used for 'ctrlRegGrav'

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 2.
frameTranslationWeightTerminal: 2. 
frameTranslationRef: [0.3, -0.2, 0.5]
frameTranslationFrameName: 'DEFAULT'

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 0., 0., 0.]
frameVelocityWeight: 0.1
frameVelocityWeightTerminal: 1
frameVelocityRef: [0., 0., 0., 0., 0., 0.]    
frameVelocityFrameName: 'DEFAULT'

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
stateLimRef: 'DEFAULT'

 # 'ctrlLim' : torque limits
ctrlBounds: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
ctrlLimRef: 'DEFAULT'

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]