# MPC parameters for end-effector circle force task
# + PyBullet or Raisim simulation


# MPC & sim parameters
simu_freq: 1000        # Simulation frequency in Hz
ctrl_freq: 250         # Control frequency
plan_freq: 250         # Planning frequency
T_tot: 1.             # Simu duration (s)
# Simulation options
DELAY_SIM: True              # Add delay in reference torques (low-level)
DELAY_OCP: True              # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: True          # Affine scaling of reference torque
NOISE_TORQUES: True          # Add Gaussian noise on reference torques
FILTER_TORQUES: False         # Moving average smoothing of reference torques
NOISE_STATE: True            # Add Gaussian noise on the measured state 
TORQUE_TRACKING: False
FILTER_STATE: False           # Moving average smoothing of reference torques
SAVE_DATA: False               # Save plot_data to npz
RECORD_SOLVER_DATA: False     # Keep trace of Vxx, Riccati gains, reg, Jacobian etc. (more data to save)
INIT_LOG: True                # Initial logs summarizing parameters
init_log_display_time: 1      # How long (s) to display the initial logs ?
LOG: True                     # Logs during simulation
log_rate: 500                 # Display sim status once very 'log_rate' sim cycles
WHICH_PLOTS: ['all']
TILT_SURFACE: False           # Tilt contact surface 
TILT_PITCH_LOCAL_DEG: -10.
RICCATI: True 


# Definition of the contact surface in the simulator
# It is aligned with the LOCAL contact frame by default
# User-defined offset expressed in the LOCAL contact frame :
contact_plane_offset: [0., 0., 0.03348]

# General
dt: 0.02                                             # OCP integration step 
N_h: 50                                             # Horizon length in nodes
maxiter: 5                                         # Max number of iterations in DDP
q0: [-0.1194, -0.1913,  0.0971, -1.3812, -0.008 ,  1.885 ,  0.3739]  # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                                          # Initial robot joint velocity


# List of contacts
contacts:
  - {
      contactModelFrameName: 'contact',       # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL_WORLD_ALIGNED',       #LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '1Dz',                # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',         # 3d vector
      contactModelRotationRef: '',            # 3d matrix
      contactModelGains: [0, 10.],             # Baumgarte stabilization gains
      active: True                            # Initially active? 
    }



# Contact model 
frame_of_interest: 'contact'


# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement', 'rotation'
WHICH_COSTS: ['force', 'stateReg', 'rotation', 'translation', 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [0., 0., 1., 0., 0., 0.]
frameForceWeight: 50
frameForceRef: [0., 0., 20, 0., 0., 0.]    
frameForceFrameName: 'contact'


 # 'stateReg' : state regularization  
stateRegWeights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: .01
stateRegWeightTerminal: .01
stateRegRef: 'DEFAULT' 

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.0001
ctrlRegRef: 'DEFAULT'  # reference not used for 'ctrlRegGrav'

 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 0.]
frameTranslationWeight: 20
frameTranslationWeightTerminal: 20.
frameTranslationRef: 'DEFAULT' 
frameTranslationFrameName: 'contact'
frameCircleTrajectoryRadius: 0.1  # in m
frameCircleTrajectoryVelocity: 1.5 # in rad/s
numberOfRounds: 1
# CIRCLE_LOCAL_PLANE: 'YZ'             # LOCAL plane in which the circle lies # x-force
# CIRCLE_LOCAL_PLANE: 'XZ'             # LOCAL plane in which the circle lies # y-force
CIRCLE_LOCAL_PLANE: 'XY'             # LOCAL plane in which the circle lies # z-force


#  # 'rotation' : end-effector frame orientation
frameRotationWeights:  [1., 1., 1.]
frameRotationWeight: 1.
frameRotationWeightTerminal: 1.
frameRotationRef: 'DEFAULT'
frameRotationFrameName: 'contact'

 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [0., 0., 1., 0., 0., 0.]
frameVelocityWeight: 1.
frameVelocityWeightTerminal: 1.
frameVelocityRef: 'DEFAULT'    
frameVelocityFrameName: 'contact'

 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 0.
stateLimWeightTerminal: 0.
stateLimRef: 'DEFAULT'

 # 'ctrlLim' : torque limits
ctrlBounds: [320, 320, 176, 176, 110, 40, 40]
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
ctrlLimRef: 'DEFAULT'

# armature
armature: [.1, .1, .1, .1, .1, .1, .0]



# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.95
alpha_max: 1.05
beta_min: -0.1
beta_max: 0.1
  # White noise on desired torque and measured state
var_u: [3.0, 3.0, 2.0, 2.0, 1.0, 0.1, 0.1]
var_q: 0.028 #x10
var_v: 0.028 #x10
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 1 # in HF cycles
  # Proportional-integral torque control gains
Kp_low: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
Ki_low: [.1, .1, .1, .1, .1, .1, .1]
Kd_low: [.00001, .00001, .00001, .00001, .00001, .00001, .00001]
u_avg_filter_length: 4 #8 # in HF cycles
x_avg_filter_length: 5  #20 #8 # in HF cycles
