# MPC parameters for EE reaching task LPF
# + PyBullet or Raisim simulation


# MPC & sim parameters
simu_freq: 5000        # Simulation frequency in Hz
ctrl_freq: 1000       # Control frequency
plan_freq: 1000          # Planning frequency
T_tot: 10            # Simu duration (s)
# Simulation options
DELAY_SIM: True              # Add delay in reference torques (low-level)
DELAY_OCP: True              # Add delay in OCP solution (i.e. ~1ms resolution time)
SCALE_TORQUES: True          # Affine scaling of reference torque
NOISE_TORQUES: True          # Add Gaussian noise on reference torques
FILTER_TORQUES: True         # Moving average smoothing of reference torques
NOISE_STATE: True            # Add Gaussian noise on the measured state 
TORQUE_TRACKING: True
FILTER_STATE: True           # Moving average smoothing of reference torques
SAVE_DATA: True               # Save plot_data to npz
RECORD_SOLVER_DATA: False     # Keep trace of Vxx, Riccati gains, reg, Jacobian etc. (more data to save)
INIT_LOG: True                # Initial logs summarizing parameters
init_log_display_time: 1      # How long (s) to display the initial logs ?
LOG: True                     # Logs during simulation
log_rate: 500                 # Display sim status once very 'log_rate' sim cycles
WHICH_PLOTS: ['f', 'ee', 'y', 'w']
TILT_SURFACE: True           # Tilt contact surface 
TILT_PITCH_LOCAL_DEG: 10.
RICCATI: False 

T_REACH: 0.5
T_TRACK: 1.
T_CONTACT: 2.
T_CIRCLE: 3.



# General 
LPF_TYPE: 0
f_c: 5                                                               # Low-pass filter cut-off frequency
tau_plus_integration: False
dt: 0.005                                          # OCP integration step 
N_h: 10                                             # Horizon length in nodes
maxiter: 10                                         # Max number of iterations in DDP
q0: [0., 0.95, 0., -1.1344640137963142, 0.2,  0.7853981633974483]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.]                         # Initial robot joint velocity


# Pin model frame name of the end-effector 
#   - Used for frame-related costs and plots generation
#   - Overrides the frame name 'DEFAULT' values below
frame_of_interest: 'contact'


# List of contacts
contacts:
  - {
      contactModelFrameName: 'contact',       # frame name in pinocchio model
      pinocchioReferenceFrame: 'LOCAL_WORLD_ALIGNED',       #LOCAL, WORLD, LOCAL_WORLD_ALIGNED
      contactModelType: '1Dz',                # 1Dx, 1Dy, 1Dz, 3D, 6D
      contactModelTranslationRef: '',         # 3d vector
      contactModelRotationRef: '',            # 3d matrix
      contactModelGains: [0, 50.],             # Baumgarte stabilization gains
      active: False                            # Initially active? 
    }
contactPosition: [0.6, 0., 0.1] # table
oPc_offset: [0., 0., 0.] 
pinRefFrame: 'LOCAL_WORLD_ALIGNED'
contactType: '1Dz'

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement', 'rotation'
WHICH_COSTS: ['force', 'translation', 'stateReg', 'ctrlRegGrav', 'stateLim'] # 'ctrlRegGrav']  

# Cost function weights and activations
 # 'force' : end-effector frame force (translation + rotation)
frameForceWeights:  [0, 0., 1., 0., 0., 0.]
frameForceWeight: 1000.
# frameForceWeightTerminal: 0.
frameForceRef: [0., 0., 50, 0., 0., 0.]    
frameForceFrameName: 'contact'


# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [0.2, 0.2, 0.2, 0.1, 0.1, 0.1, 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.01
stateRegWeightTerminal: 0.01
stateRegRef: 'DEFAULT'

 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.0001
ctrlRegWeightTerminal: 0.0001
ctrlRegRef: 'DEFAULT'  # default 0 if None

# 'wReg' : unfiltered torque regularization
wRegWeight: 0.0000001
wRegRef: 'gravity'

# 'wLim' : unfiltered torque limit
wLimWeight: 0


 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 10.
frameTranslationWeightTerminal: 100.
frameTranslationRef: 'DEFAULT'
frameTranslationFrameName: 'contact'
frameCircleTrajectoryRadius: 0.1  # in m
frameCircleTrajectoryVelocity: 3 # in rad/s
numberOfRounds: 10
CIRCLE_LOCAL_PLANE: 'XY'


 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 1., 1., 1.]
frameVelocityWeight: 0.5
frameVelocityWeightTerminal: 1.
frameVelocityRef: 'DEFAULT'    
frameVelocityFrameName: 'contact'


 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 1000.
stateLimWeightTerminal: 1000.
coef_xlim: 0.85

 # 'ctrlLim' : torque limits
ctrlLimWeights: [1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 0.
coef_ulim: 1


# armature
armature:  [.0, .0, .0, .0, .0, 0.]


# # # # # # # # # # # # # # # # # # # # # #
# Low-level simulation (actuation model)  #
# # # # # # # # # # # # # # # # # # # # # #
  # Scaling of desired torque
alpha_min: 0.95
alpha_max: 1.05
beta_min: -0.1
beta_max: 0.1
  # White noise on desired torque and measured state
var_u: [3.0, 3.0, 2.0, 2.0, 1.0, 0.1]
var_q: 0.028 #x10
var_v: 0.028 #x10
var_aug: [0, 0, 0, 0, 0, 0, 0] # LPF
  # Buffer for torque delay
delay_OCP_ms: 1    # in ms
delay_sim_cycle: 1 # in HF cycles
  # Proportional-integral torque control gains
Kp_low: [1, 1, 1, 1, 1, 1]
Ki_low: [0., 0., 0., 0., 0., 0.]
Kd_low: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
u_avg_filter_length: 4 #8 # in HF cycles
x_avg_filter_length: 5  #20 #8 # in HF cycles